In [1]:
print('Hello')

Hello


In [2]:
print('Hello')

Hello


In [6]:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
type(data)

numpy.ndarray

In [7]:
import sys
print(sys.executable)

c:\Users\ShivaGanesna\Downloads\IGTMUAD\20251208\.venv\Scripts\python.exe


In [ ]:
zeros = np.zeros((3, 4))  # Bias initialization
ones = np.ones((2, 3))
random_weights = np.random.randn(5, 3) * 0.01  # Xavier/He initialization
print(f"\nZeros (3x4):\n{zeros}")
print(f"Random weights (5x3):\n{random_weights}")


Zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Random weights (5x3):
[[-0.02031551 -0.01273541  0.01185838]
 [-0.03157564 -0.00376143  0.00339887]
 [-0.00935313 -0.00174757  0.00944882]
 [ 0.02225174  0.003825   -0.0018602 ]
 [-0.00326574 -0.00692558  0.00228502]]


In [ ]:
sequence = np.arange(0, 10, 7)  # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)  # 5 evenly spaced points
print(f"\nArange: {sequence}")
print(f"Linspace: {linspace}")


Arange: [0 7]
Linspace: [0.   0.25 0.5  0.75 1.  ]


 Q3: Difference between reshape() and flatten()?
 A: reshape() can create any shape, returns view if possible
    flatten() always returns 1D copy
    ravel() returns 1D view (faster, but changes affect original)

Q1: Why vectorization? Why not use Python loops?
A: Vectorized NumPy is 10-100x faster! Uses C/Fortran underneath, SIMD instructions.
   Example: np.sum(arr) vs sum(arr) - NumPy is ~50x faster.

In [ ]:
seq = np.arange(0,100,4)
print(seq)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


In [ ]:
seq.shape
x = seq.reshape(1,5,5)
print(x)

[[[ 0  4  8 12 16]
  [20 24 28 32 36]
  [40 44 48 52 56]
  [60 64 68 72 76]
  [80 84 88 92 96]]]


In [ ]:
data = {
    'user_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'age': [25, 35, np.nan, 45, 28, 52, 38, np.nan],
    'income': [50000, 60000, 55000, 80000, 45000, 90000, 65000, 70000],
    'purchased': [1, 0, 1, 1, 0, 1, 0, 1],
    'signup_date': ['2023-01-15', '2023-02-20', '2023-01-10', '2023-03-05',
                    '2023-02-28', '2023-01-20', '2023-03-15', '2023-02-10']
}

In [ ]:
import pandas as pd
df = pd.DataFrame(data)

In [ ]:
df

user_id   age  income  purchased signup_date
0        1  25.0   50000          1  2023-01-15
1        2  35.0   60000          0  2023-02-20
2        3   NaN   55000          1  2023-01-10
3        4  45.0   80000          1  2023-03-05
4        5  28.0   45000          0  2023-02-28
5        6  52.0   90000          1  2023-01-20
6        7  38.0   65000          0  2023-03-15
7        8   NaN   70000          1  2023-02-10

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   user_id      8 non-null      int64  
 1   age          6 non-null      float64
 2   income       8 non-null      int64  
 3   purchased    8 non-null      int64  
 4   signup_date  8 non-null      object 
dtypes: float64(1), int64(3), object(1)
memory usage: 452.0+ bytes


In [ ]:
df.describe()

user_id        age        income  purchased
count  8.00000   6.000000      8.000000   8.000000
mean   4.50000  37.166667  64375.000000   0.625000
std    2.44949  10.186592  15221.577729   0.517549
min    1.00000  25.000000  45000.000000   0.000000
25%    2.75000  29.750000  53750.000000   0.000000
50%    4.50000  36.500000  62500.000000   1.000000
75%    6.25000  43.250000  72500.000000   1.000000
max    8.00000  52.000000  90000.000000   1.000000

In [ ]:
df.isnull().sum() 

user_id        0
age            2
income         0
purchased      0
signup_date    0
dtype: int64

In [ ]:
data2 = {
    'customer_id': range(1, 21),
    'city': ['NYC', 'LA', 'NYC', 'Chicago', 'LA'] * 4,
    'age_group': ['18-25', '26-35', '36-45', '18-25', '26-35'] * 4,
    'purchase_amount': np.random.randint(10, 200, 20),
    'num_purchases': np.random.randint(1, 10, 20)
}
df2 = pd.DataFrame(data2)

print("Sample data:")
print(df2.head())

# Group by city and calculate mean
print("\n\nAverage purchase amount by city:")
print(df2.groupby('city')['purchase_amount'].mean())

# Multiple aggregations
print("\n\nMultiple aggregations by city:")
print(df2.groupby('city')['purchase_amount'].agg(['mean', 'sum', 'count']))

# Group by multiple columns
print("\n\nGroup by city AND age_group:")
print(df2.groupby(['city', 'age_group'])['purchase_amount'].mean())

# Custom aggregation with agg()
print("\n\nCustom aggregations:")
result = df2.groupby('city').agg({
    'purchase_amount': ['mean', 'sum'],
    'num_purchases': ['count', 'max']
})
print(result)

Sample data:
   customer_id     city age_group  purchase_amount  num_purchases
0            1      NYC     18-25              194              6
1            2       LA     26-35               43              6
2            3      NYC     36-45               85              8
3            4  Chicago     18-25               67              9
4            5       LA     26-35              160              9


Average purchase amount by city:
city
Chicago     74.00
LA         120.50
NYC        122.75
Name: purchase_amount, dtype: float64


Multiple aggregations by city:
           mean  sum  count
city                       
Chicago   74.00  296      4
LA       120.50  964      8
NYC      122.75  982      8


Group by city AND age_group:
city     age_group
Chicago  18-25         74.0
LA       26-35        120.5
NYC      18-25        146.0
         36-45         99.5
Name: purchase_amount, dtype: float64


Custom aggregations:
        purchase_amount      num_purchases    
                

In [ ]:
df2

customer_id     city age_group  purchase_amount  num_purchases
0             1      NYC     18-25              194              6
1             2       LA     26-35               43              6
2             3      NYC     36-45               85              8
3             4  Chicago     18-25               67              9
4             5       LA     26-35              160              9
5             6      NYC     18-25               87              5
6             7       LA     26-35              119              3
7             8      NYC     36-45               56              7
8             9  Chicago     18-25               65              9
9            10       LA     26-35              165              5
10           11      NYC     18-25              169              6
11           12       LA     26-35              186              7
12           13      NYC     36-45              177              4
13           14  Chicago     18-25               42              2
14           15       LA     26-35               89              7
15           16      NYC     18-25              134              9
16           17       LA     26-35              165              8
17           18      NYC     36-45               80              2
18           19  Chicago     18-25              122              6
19           20       LA     26-35               37              8

In [ ]:
print(df2.groupby('city')['purchase_amount'].agg(['mean', 'sum', 'count']))

           mean  sum  count
city                       
Chicago   74.00  296      4
LA       120.50  964      8
NYC      122.75  982      8


Q3: How to handle duplicate column names after merge?

A: Use suffixes parameter: pd.merge(df1, df2, suffixes=('_left', '_right'))

Q4: Real scenario: You have user data and transaction data. How to combine?

A: pd.merge(users, transactions, on='user_id', how='left')
   Left join keeps all users even if no transactions


. Why Async Matters for ML Serving

Without async: 10 users × 200ms = 2 seconds
With async: All 10 users in ~200ms (10× faster!)

In [ ]:
import os
print(os.curdir)

.


np.array more efficient in memory and speed , 
Stored in contiguous memory, 
can perform direct mathematical operations on array
NumPy has hundreds of methods for math, stats, linear algebra



In [ ]:

import numpy as np

# 1D array
a = np.array([1, 2, 3])
print('Hello')

# 2D array
b = np.array([[1, 2], [3, 4]])
print(b)

# array filled with zeros
z = np.zeros((3, 2))
print(z)

# array filled with ones
o = np.ones((2, 3))
print(o)

# random array
r = np.random.rand(3, 3)
print(r)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(a - b)
print(a / b)
print(a ** 2)

# scalar operations
print(a * 10)
