In [1]:
import numpy as np

## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ##1 row and 5 columns
arr2

array([1, 2, 3, 4, 5])

In [9]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

y =np.arange(0,10,2).reshape(5,1)
y

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [11]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [12]:
x = np.array([1,2,3,4,5,6,7,8,9,0])
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [13]:
x.shape

(10,)

In [14]:
x[0]

np.int64(1)

In [17]:
x.reshape(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [19]:
x[0]
x.shape

(10,)

In [35]:
y = x.reshape(-1,1)
y.shape
y

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9],
       [0]])

In [37]:
y = x.reshape(1,10)
y.shape
y

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]])